site_name: Docs

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/MSD.LIVE.STACK.png
  favicon: assets/favicon.ico

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

  palette:
    - scheme: default
      primary: white
      accent: blue

extra_css:
  - styles/nav.css

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - CLI: 
    - Help: cli/cli_help.md
    - Using a Virtual Environment: cli/venv.md
    - Installing the CLI: cli/installation.md
    - Using the CLI: cli/cli_usage.md
    - Running the CLI Behing a Proxy: cli/proxy_run_cli.md
  - Dataset Notebooks: dataset_notebooks.md
  - Tutorials: tutorials.md
  - Articles: articles.md
  - Webinars: webinars.md


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true