site_name: Docs

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/MSD.LIVE.STACK.png
  favicon: assets/favicon.ico

  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight

  palette:
    - scheme: default
      primary: white
      accent: blue

plugins:
  - search

extra_css:
  - styles/nav.css

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - CLI:
    - cli/cli_help.md
    - cli/venv.md
    - cli/installation.md
    - cli/cli_usage.md
    - cli/proxy_run_cli.md
  - Dataset Notebooks:
    - dataset_notebooks/dataset_notebooks.md
    - dataset_notebooks/create_notebooks.md
    - dataset_notebooks/enable_exploration.md
    - dataset_notebooks/notebook_lab.md
    - dataset_notebooks/prepackaged_code.md
    - dataset_notebooks/using_notebooks.md
  - Tutorials: tutorials.md
  - Articles: articles.md
  - Webinars: webinars.md
  - Spacial Metadata: spacial_metadata.md


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true