site_name: Docs

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/MSD.LIVE.horiz.svg
  favicon: assets/favicon.ico

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

  palette:
    - scheme: default
      primary: white
      accent: blue

extra_css:
  - styles/nav.css

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Resources: resources.md
  - CLI: 
    - Help: cli/cli_help.md
    - Using a Virtual Environment: cli/venv.md

  - Dataset Notebooks: dataset_notebooks.md


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true