site_name: Docs

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/MSD.LIVE.horiz.svg
  favicon: assets/favicon.ico

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

  palette:
    - scheme: default
      primary: white
      accent: blue

extra_css:
  - styles/nav.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Resources: resources.md
  - CLI Help: cli-help.md
  - Dataset Notebooks: dataset-notebooks.md
